name: Q3 Workflow
run-name: ${{ github.actor }} teste Q3 🚀

on: [push]

permissions:
  contents: write

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest

    steps:
    # Vérifier le dépôt
    - name: Checkout repository
      uses: actions/checkout@v3

    # Créer le fichier Q3_archive_java.txt avec nom, prénom et contenu de Q3.java
    - name: Create Q3 archive file
      run: |
        echo "Nom et prénom : Clémentin LY" > Q3_archive_java.txt
        echo "" >> Q3_archive_java.txt
        echo "Contenu de Q3.java :" >> Q3_archive_java.txt
        cat Q3.java >> Q3_archive_java.txt

    # Push
    - name: Commit and push changes
      run: |
        git config --global user.name "ClemLy"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git stash                         # Sauvegarder temporairement les modifications locales
        git pull --rebase origin main     # Récupérer les changements distants
        git stash pop                     # Réappliquer les modifications locales
        git add Q4_archive_*.txt
        git commit -m "Add Q4 archive file"
        git push
